#query_one
query($id: ID!) {
  user(id: $id) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}

#query_all
query {
  users(first: 2) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}

#query_mixture
query($id: ID!, $sponsorId: ID!) {
  user(id: $id) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
  sponsor: user(id: $sponsorId) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}

#insert
mutation(
  $name: String!
  $age: Int
  $sex: String
  $hobby: [String]!
  $sponsorId: ID
) {
  createUser(
    name: $name
    age: $age
    sex: $sex
    hobby: $hobby
    sponsorId: $sponsorId
  ) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}

#update
mutation(
  $id: ID!
  $name: String
  $age: Int
  $sex: String
  $hobby: [String]
  $sponsorId: ID
) {
  updateUser(
    id: $id
    name: $name
    age: $age
    sex: $sex
    hobby: $hobby
    sponsorId: $sponsorId
  ) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}

#delete
mutation($id: ID!) {
  deleteUser(id: $id) {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}
