type Query {
  users(first: Int!): [User!]!
  user(id: ID!): User!
}

type User {
  id: ID!
  name: String!
  age: Int
  sex: String,
  hobby: [String]!,
  sponsorId: ID
}

type Mutation {
  createUser(name: String!, age: Int, sex: String, hobby: [String]!, sponsorId: ID): User!
  updateUser(id: ID!, name: String, age: Int, sex: String, hobby: [String], sponsorId: ID): User!
  deleteUser(id: ID!): User!
}

subscription {
  users {
    id
    name
    sex
    age
    hobby
    sponsorId
  }
}
